### ISSUE TITLE
Using BlueALSA with alsa_out/alsa_in to bridge BT audio to JACK

### ISSUE THREAD

**Issue by unfa** [Arkq/bluez-alsa#326] opened 2020-04-23 23:03 UTC
Is it possible to use BlueALSA to bridge Bluetooth audio devices to the JACK Audio Connection Kit?

The alsa_out / alsa_in programs should be able to do it, but I wasn't able to get it to work.

Here's results:

```
$ alsa_out -d bluealsa
D: ../../../src/asound/bluealsa-pcm.c:671: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Setting constraints
WARNING: buffer size does not match: (requested 2048, got 9600)
WARNING: period size does not match: (requested 1024, got 1066)
D: ../../../src/asound/bluealsa-pcm.c:368: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Initializing HW
D: ../../../src/asound/bluealsa-pcm.c:394: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: FIFO buffer size: 4096
D: ../../../src/asound/bluealsa-pcm.c:397: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Selected HW buffer: 9 periods x 4264 bytes <= 38400 bytes
D: ../../../src/asound/bluealsa-pcm.c:415: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Initializing SW
D: ../../../src/asound/bluealsa-pcm.c:415: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Initializing SW
D: ../../../src/asound/bluealsa-pcm.c:415: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Initializing SW
D: ../../../src/asound/bluealsa-pcm.c:437: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Prepared
D: ../../../src/asound/bluealsa-pcm.c:415: /org/bluealsa/hci0/dev_00_0A_45_0E_90_F7/a2dpsrc/sink: Initializing SW
*** Segmentation fault
Register dump:

 RAX: 000055593964e768   RBX: 00007f05bc086740   RCX: 000000000000026d
 RDX: 00007ffea9e04000   RSI: 0000000000000004   RDI: 0000000000000008
 RBP: 0000000000000000   R8 : 000000007fffffff   R9 : 00005559396286d0
 R10: 00007f05bc086740   R11: 00007ffea9dfd310   R12: 0000000000001000
 R13: 00007f05bc0866e0   R14: 000055593964a6b0   R15: 00007ffea9dfd260
 RSP: 00007ffea9dfd1a8

 RIP: 00007f05bc08674b   EFLAGS: 00010213

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000e   Error: 00000004   OldMask: 00001000   CR2: a9e04000

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00000000
 RIP: 00000000   RDP: 00000000

 ST(0) 0000 0000000000000000   ST(1) 0000 0000000000000000
 ST(2) 0000 0000000000000000   ST(3) 0000 0000000000000000
 ST(4) 0000 0000000000000000   ST(5) 0000 0000000000000000
 ST(6) 0000 0000000000000000   ST(7) 0000 0000000000000000
 mxcsr: 1fa3
 XMM0:  0000000000000000000000003f800000 XMM1:  0000000000000000000000003f800000
 XMM2:  0000000000000000000000003f800000 XMM3:  0000000000000000000000003f800000
 XMM4:  0000000000000000000000003f800000 XMM5:  0000000000000000000000003f800000
 XMM6:  0000000000000000000000003f800000 XMM7:  0000000000000000000000003f800000
 XMM8:  0000000000000000000000003f800000 XMM9:  0000000000000000000000003f800000
 XMM10: 0000000000000000000000003f800000 XMM11: 0000000000000000000000003f800000
 XMM12: 0000000000000000000000003f800000 XMM13: 0000000000000000000000003f800000
 XMM14: 0000000000000000000000003f800000 XMM15: 0000000000000000000000003f800000

Backtrace:
/usr/lib/libasound.so.2(snd_pcm_lfloat_convert_float_integer+0x3fb)[0x7f05bc08674b]
/usr/lib/libasound.so.2(+0x79f12)[0x7f05bc085f12]
/usr/lib/libasound.so.2(+0x5d472)[0x7f05bc069472]
/usr/lib/libasound.so.2(+0x50bc4)[0x7f05bc05cbc4]
/usr/lib/libasound.so.2(+0x5d974)[0x7f05bc069974]
alsa_out(+0x370e)[0x5559381cc70e]
alsa_out(+0x2339)[0x5559381cb339]
/usr/lib/libc.so.6(__libc_start_main+0xf3)[0x7f05bbbb9153]
alsa_out(+0x29ae)[0x5559381cb9ae]

Memory map:

5559381c9000-5559381cb000 r--p 00000000 00:18 4925057                    /usr/bin/alsa_out
5559381cb000-5559381cf000 r-xp 00002000 00:18 4925057                    /usr/bin/alsa_out
5559381cf000-5559381d1000 r--p 00006000 00:18 4925057                    /usr/bin/alsa_out
5559381d1000-5559381d2000 r--p 00007000 00:18 4925057                    /usr/bin/alsa_out
5559381d2000-5559381d3000 rw-p 00008000 00:18 4925057                    /usr/bin/alsa_out
555939605000-555939668000 rw-p 00000000 00:00 0                          [heap]
7f05af188000-7f05b4000000 rw-s 00000000 00:25 128                        /dev/shm/jack-1000-0
7f05b4000000-7f05b4021000 rw-p 00000000 00:00 0 
7f05b4021000-7f05b8000000 ---p 00000000 00:00 0 
7f05bb473000-7f05bb477000 r--p 00000000 00:18 4916001                    /usr/lib/libgpg-error.so.0.27.0
7f05bb477000-7f05bb48a000 r-xp 00004000 00:18 4916001                    /usr/lib/libgpg-error.so.0.27.0
7f05bb48a000-7f05bb493000 r--p 00017000 00:18 4916001                    /usr/lib/libgpg-error.so.0.27.0
7f05bb493000-7f05bb494000 ---p 00020000 00:18 4916001                    /usr/lib/libgpg-error.so.0.27.0
7f05bb494000-7f05bb495000 r--p 00020000 00:18 4916001                    /usr/lib/libgpg-error.so.0.27.0
7f05bb495000-7f05bb496000 rw-p 00021000 00:18 4916001                    /usr/lib/libgpg-error.so.0.27.0
7f05bb496000-7f05bb4a2000 r--p 00000000 00:18 4916043                    /usr/lib/libgcrypt.so.20.2.5
7f05bb4a2000-7f05bb570000 r-xp 0000c000 00:18 4916043                    /usr/lib/libgcrypt.so.20.2.5
7f05bb570000-7f05bb5ac000 r--p 000da000 00:18 4916043                    /usr/lib/libgcrypt.so.20.2.5
7f05bb5ac000-7f05bb5ad000 ---p 00116000 00:18 4916043                    /usr/lib/libgcrypt.so.20.2.5
7f05bb5ad000-7f05bb5af000 r--p 00116000 00:18 4916043                    /usr/lib/libgcrypt.so.20.2.5
7f05bb5af000-7f05bb5b4000 rw-p 00118000 00:18 4916043                    /usr/lib/libgcrypt.so.20.2.5
7f05bb5b4000-7f05bb5b7000 r--p 00000000 00:18 4892557                    /usr/lib/liblz4.so.1.9.2
7f05bb5b7000-7f05bb5d1000 r-xp 00003000 00:18 4892557                    /usr/lib/liblz4.so.1.9.2
7f05bb5d1000-7f05bb5d4000 r--p 0001d000 00:18 4892557                    /usr/lib/liblz4.so.1.9.2
7f05bb5d4000-7f05bb5d5000 r--p 0001f000 00:18 4892557                    /usr/lib/liblz4.so.1.9.2
7f05bb5d5000-7f05bb5d6000 rw-p 00020000 00:18 4892557                    /usr/lib/liblz4.so.1.9.2
7f05bb5d6000-7f05bb5d9000 r--p 00000000 00:18 4892492                    /usr/lib/liblzma.so.5.2.4
7f05bb5d9000-7f05bb5f0000 r-xp 00003000 00:18 4892492                    /usr/lib/liblzma.so.5.2.4
7f05bb5f0000-7f05bb5fb000 r--p 0001a000 00:18 4892492                    /usr/lib/liblzma.so.5.2.4
7f05bb5fb000-7f05bb5fc000 ---p 00025000 00:18 4892492                    /usr/lib/liblzma.so.5.2.4
7f05bb5fc000-7f05bb5fd000 r--p 00025000 00:18 4892492                    /usr/lib/liblzma.so.5.2.4
7f05bb5fd000-7f05bb5fe000 rw-p 00026000 00:18 4892492                    /usr/lib/liblzma.so.5.2.4
7f05bb5fe000-7f05bb60f000 r--p 00000000 00:18 6532646                    /usr/lib/libsystemd.so.0.27.1
7f05bb60f000-7f05bb67c000 r-xp 00011000 00:18 6532646                    /usr/lib/libsystemd.so.0.27.1
7f05bb67c000-7f05bb6a0000 r--p 0007e000 00:18 6532646                    /usr/lib/libsystemd.so.0.27.1
7f05bb6a0000-7f05bb6a3000 r--p 000a1000 00:18 6532646                    /usr/lib/libsystemd.so.0.27.1
7f05bb6a3000-7f05bb6a4000 rw-p 000a4000 00:18 6532646                    /usr/lib/libsystemd.so.0.27.1
7f05bb6a4000-7f05bb6a5000 rw-p 00000000 00:00 0 
7f05bb6a5000-7f05bb6a6000 r--p 00000000 00:18 4888112                    /usr/lib/libSegFault.so
7f05bb6a6000-7f05bb6a9000 r-xp 00001000 00:18 4888112                    /usr/lib/libSegFault.so
7f05bb6a9000-7f05bb6aa000 r--p 00004000 00:18 4888112                    /usr/lib/libSegFault.so
7f05bb6aa000-7f05bb6ab000 r--p 00004000 00:18 4888112                    /usr/lib/libSegFault.so
7f05bb6ab000-7f05bb6ac000 rw-p 00005000 00:18 4888112                    /usr/lib/libSegFault.so
7f05bb6ac000-7f05bb6ba000 r--p 00000000 00:18 6068224                    /usr/lib/libdbus-1.so.3.19.11
7f05bb6ba000-7f05bb6e2000 r-xp 0000e000 00:18 6068224                    /usr/lib/libdbus-1.so.3.19.11
7f05bb6e2000-7f05bb6f3000 r--p 00036000 00:18 6068224                    /usr/lib/libdbus-1.so.3.19.11
7f05bb6f3000-7f05bb6f5000 r--p 00046000 00:18 6068224                    /usr/lib/libdbus-1.so.3.19.11
7f05bb6f5000-7f05bb6f6000 rw-p 00048000 00:18 6068224                    /usr/lib/libdbus-1.so.3.19.11
7f05bb74d000-7f05bb750000 r--p 00000000 00:18 6822569                    /usr/lib/alsa-lib/libasound_module_pcm_bluealsa.so
7f05bb750000-7f05bb754000 r-xp 00003000 00:18 6822569                    /usr/lib/alsa-lib/libasound_module_pcm_bluealsa.so
7f05bb754000-7f05bb756000 r--p 00007000 00:18 6822569                    /usr/lib/alsa-lib/libasound_module_pcm_bluealsa.so
7f05bb756000-7f05bb757000 r--p 00008000 00:18 6822569                    /usr/lib/alsa-lib/libasound_module_pcm_bluealsa.so
7f05bb757000-7f05bb758000 rw-p 00009000 00:18 6822569                    /usr/lib/alsa-lib/libasound_module_pcm_bluealsa.so
7f05bb758000-7f05bb759000 ---p 00000000 00:00 0 
7f05bb759000-7f05bb7d9000 rw-p 00000000 00:00 0 
7f05bb7d9000-7f05bb81b000 rw-s 00000000 00:25 354                        /dev/shm/jack_db/__db.003
7f05bb81b000-7f05bb907000 rw-s 00000000 00:25 262                        /dev/shm/jack_db/__db.001
7f05bb907000-7f05bb908000 ---p 00000000 00:00 0 
7f05bb908000-7f05bb98c000 rw-p 00000000 00:00 0 
7f05bb98c000-7f05bb98f000 r--p 00000000 00:18 4637080                    /usr/lib/libgcc_s.so.1
7f05bb98f000-7f05bb9a0000 r-xp 00003000 00:18 4637080                    /usr/lib/libgcc_s.so.1
7f05bb9a0000-7f05bb9a4000 r--p 00014000 00:18 4637080                    /usr/lib/libgcc_s.so.1
7f05bb9a4000-7f05bb9a5000 r--p 00017000 00:18 4637080                    /usr/lib/libgcc_s.so.1
7f05bb9a5000-7f05bb9a6000 rw-p 00018000 00:18 4637080                    /usr/lib/libgcc_s.so.1
7f05bb9a6000-7f05bb9a8000 rw-p 00000000 00:00 0 
7f05bb9a8000-7f05bba3e000 r--p 00000000 00:18 4637110                    /usr/lib/libstdc++.so.6.0.27
7f05bba3e000-7f05bbb37000 r-xp 00096000 00:18 4637110                    /usr/lib/libstdc++.so.6.0.27
7f05bbb37000-7f05bbb81000 r--p 0018f000 00:18 4637110                    /usr/lib/libstdc++.so.6.0.27
7f05bbb81000-7f05bbb8e000 r--p 001d8000 00:18 4637110                    /usr/lib/libstdc++.so.6.0.27
7f05bbb8e000-7f05bbb8f000 rw-p 001e5000 00:18 4637110                    /usr/lib/libstdc++.so.6.0.27
7f05bbb8f000-7f05bbb92000 rw-p 00000000 00:00 0 
7f05bbb92000-7f05bbbb7000 r--p 00000000 00:18 4888117                    /usr/lib/libc-2.30.so
7f05bbbb7000-7f05bbd04000 r-xp 00025000 00:18 4888117                    /usr/lib/libc-2.30.so
7f05bbd04000-7f05bbd4e000 r--p 00172000 00:18 4888117                    /usr/lib/libc-2.30.so
7f05bbd4e000-7f05bbd4f000 ---p 001bc000 00:18 4888117                    /usr/lib/libc-2.30.so
7f05bbd4f000-7f05bbd52000 r--p 001bc000 00:18 4888117                    /usr/lib/libc-2.30.so
7f05bbd52000-7f05bbd55000 rw-p 001bf000 00:18 4888117                    /usr/lib/libc-2.30.so
7f05bbd55000-7f05bbd59000 rw-p 00000000 00:00 0 
7f05bbd59000-7f05bbd68000 r--p 00000000 00:18 4888132                    /usr/lib/libm-2.30.so
7f05bbd68000-7f05bbe04000 r-xp 0000f000 00:18 4888132                    /usr/lib/libm-2.30.so
7f05bbe04000-7f05bbe9d000 r--p 000ab000 00:18 4888132                    /usr/lib/libm-2.30.so
7f05bbe9d000-7f05bbe9e000 r--p 00143000 00:18 4888132                    /usr/lib/libm-2.30.so
7f05bbe9e000-7f05bbe9f000 rw-p 00144000 00:18 4888132                    /usr/lib/libm-2.30.so
7f05bbe9f000-7f05bbea0000 r--p 00000000 00:18 6086501                    /usr/lib/libsamplerate.so.0.1.8
7f05bbea0000-7f05bbea4000 r-xp 00001000 00:18 6086501                    /usr/lib/libsamplerate.so.0.1.8
7f05bbea4000-7f05bc00a000 r--p 00005000 00:18 6086501                    /usr/lib/libsamplerate.so.0.1.8
7f05bc00a000-7f05bc00b000 r--p 0016a000 00:18 6086501                    /usr/lib/libsamplerate.so.0.1.8
7f05bc00b000-7f05bc00c000 rw-p 0016b000 00:18 6086501                    /usr/lib/libsamplerate.so.0.1.8
7f05bc00c000-7f05bc039000 r--p 00000000 00:18 6067894                    /usr/lib/libasound.so.2.0.0
7f05bc039000-7f05bc0b2000 r-xp 0002d000 00:18 6067894                    /usr/lib/libasound.so.2.0.0
7f05bc0b2000-7f05bc0dd000 r--p 000a6000 00:18 6067894                    /usr/lib/libasound.so.2.0.0
7f05bc0dd000-7f05bc0e5000 r--p 000d0000 00:18 6067894                    /usr/lib/libasound.so.2.0.0
7f05bc0e5000-7f05bc0e6000 rw-p 000d8000 00:18 6067894                    /usr/lib/libasound.so.2.0.0
7f05bc0e6000-7f05bc0e7000 r--p 00000000 00:18 4888126                    /usr/lib/libdl-2.30.so
7f05bc0e7000-7f05bc0e8000 r-xp 00001000 00:18 4888126                    /usr/lib/libdl-2.30.so
7f05bc0e8000-7f05bc0e9000 r--p 00002000 00:18 4888126                    /usr/lib/libdl-2.30.so
7f05bc0e9000-7f05bc0ea000 r--p 00002000 00:18 4888126                    /usr/lib/libdl-2.30.so
7f05bc0ea000-7f05bc0eb000 rw-p 00003000 00:18 4888126                    /usr/lib/libdl-2.30.so
7f05bc0eb000-7f05bc0ed000 rw-p 00000000 00:00 0 
7f05bc0ed000-7f05bc0f0000 r--p 00000000 00:18 4888169                    /usr/lib/librt-2.30.so
7f05bc0f0000-7f05bc0f4000 r-xp 00003000 00:18 4888169                    /usr/lib/librt-2.30.so
7f05bc0f4000-7f05bc0f6000 r--p 00007000 00:18 4888169                    /usr/lib/librt-2.30.so
7f05bc0f6000-7f05bc0f7000 r--p 00008000 00:18 4888169                    /usr/lib/librt-2.30.so
7f05bc0f7000-7f05bc0f8000 rw-p 00009000 00:18 4888169                    /usr/lib/librt-2.30.so
7f05bc0f8000-7f05bc122000 r--p 00000000 00:18 4907131                    /usr/lib/libdb-5.3.so
7f05bc122000-7f05bc266000 r-xp 0002a000 00:18 4907131                    /usr/lib/libdb-5.3.so
7f05bc266000-7f05bc2ab000 r--p 0016e000 00:18 4907131                    /usr/lib/libdb-5.3.so
7f05bc2ab000-7f05bc2ac000 ---p 001b3000 00:18 4907131                    /usr/lib/libdb-5.3.so
7f05bc2ac000-7f05bc2b6000 r--p 001b3000 00:18 4907131                    /usr/lib/libdb-5.3.so
7f05bc2b6000-7f05bc2b7000 rw-p 001bd000 00:18 4907131                    /usr/lib/libdb-5.3.so
7f05bc2b7000-7f05bc2ba000 r--p 00000000 00:18 970015                     /usr/lib/libopus.so.0.8.0
7f05bc2ba000-7f05bc300000 r-xp 00003000 00:18 970015                     /usr/lib/libopus.so.0.8.0
7f05bc300000-7f05bc313000 r--p 00049000 00:18 970015                     /usr/lib/libopus.so.0.8.0
7f05bc313000-7f05bc314000 r--p 0005b000 00:18 970015                     /usr/lib/libopus.so.0.8.0
7f05bc314000-7f05bc315000 rw-p 0005c000 00:18 970015                     /usr/lib/libopus.so.0.8.0
7f05bc315000-7f05bc32c000 r-xp 00000000 00:18 80881                      /usr/lib/libcelt0.so.2.0.0
7f05bc32c000-7f05bc52c000 ---p 00017000 00:18 80881                      /usr/lib/libcelt0.so.2.0.0
7f05bc52c000-7f05bc52d000 r--p 00017000 00:18 80881                      /usr/lib/libcelt0.so.2.0.0
7f05bc52d000-7f05bc52e000 rw-p 00018000 00:18 80881                      /usr/lib/libcelt0.so.2.0.0
7f05bc52e000-7f05bc535000 r--p 00000000 00:18 4888161                    /usr/lib/libpthread-2.30.so
7f05bc535000-7f05bc545000 r-xp 00007000 00:18 4888161                    /usr/lib/libpthread-2.30.so
7f05bc545000-7f05bc54a000 r--p 00017000 00:18 4888161                    /usr/lib/libpthread-2.30.so
7f05bc54a000-7f05bc54b000 r--p 0001b000 00:18 4888161                    /usr/lib/libpthread-2.30.so
7f05bc54b000-7f05bc54c000 rw-p 0001c000 00:18 4888161                    /usr/lib/libpthread-2.30.so
7f05bc54c000-7f05bc550000 rw-p 00000000 00:00 0 
7f05bc550000-7f05bc55c000 r--p 00000000 00:18 4925130                    /usr/lib/libjack.so.0.1.0
7f05bc55c000-7f05bc584000 r-xp 0000c000 00:18 4925130                    /usr/lib/libjack.so.0.1.0
7f05bc584000-7f05bc59a000 r--p 00034000 00:18 4925130                    /usr/lib/libjack.so.0.1.0
7f05bc59a000-7f05bc59d000 r--p 00049000 00:18 4925130                    /usr/lib/libjack.so.0.1.0
7f05bc59d000-7f05bc59e000 rw-p 0004c000 00:18 4925130                    /usr/lib/libjack.so.0.1.0
7f05bc59e000-7f05bc5a0000 rw-p 00000000 00:00 0 
7f05bc5a1000-7f05bc5a2000 rw-s 00000000 00:25 1111                       /dev/shm/jack_sem.1000_default_alsa_out
7f05bc5a2000-7f05bc5a3000 rw-s 00000000 00:25 1196                       /dev/shm/jack-1000-3 (deleted)
7f05bc5a3000-7f05bc5a4000 rw-s 00000000 00:25 142                        /dev/shm/jack-1000-1
7f05bc5a4000-7f05bc5b6000 rw-s 00000000 00:25 21                         /dev/shm/jack-shm-registry
7f05bc5b6000-7f05bc5b7000 rw-s 00000000 00:25 582                        /dev/shm/jack_sem.1000_default_a2j
7f05bc5b7000-7f05bc5b8000 rw-s 00000000 00:25 499                        /dev/shm/jack_sem.1000_default_dbusapi
7f05bc5b8000-7f05bc5b9000 rw-s 00000000 00:25 482                        /dev/shm/jack_sem.1000_default_freewheel
7f05bc5b9000-7f05bc5f7000 rw-s 00000000 00:25 272                        /dev/shm/jack_db/__db.002
7f05bc5f7000-7f05bc5f9000 r--p 00000000 00:18 4888106                    /usr/lib/ld-2.30.so
7f05bc5f9000-7f05bc618000 r-xp 00002000 00:18 4888106                    /usr/lib/ld-2.30.so
7f05bc618000-7f05bc620000 r--p 00021000 00:18 4888106                    /usr/lib/ld-2.30.so
7f05bc620000-7f05bc621000 rw-s 00000000 00:25 387                        /dev/shm/jack_sem.1000_default_system
7f05bc621000-7f05bc622000 r--p 00029000 00:18 4888106                    /usr/lib/ld-2.30.so
7f05bc622000-7f05bc623000 rw-p 0002a000 00:18 4888106                    /usr/lib/ld-2.30.so
7f05bc623000-7f05bc624000 rw-p 00000000 00:00 0 
7ffea9de3000-7ffea9e04000 rw-p 00000000 00:00 0                          [stack]
7ffea9fd2000-7ffea9fd5000 r--p 00000000 00:00 0                          [vvar]
7ffea9fd5000-7ffea9fd6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
Segmentation fault (core dumped)
```

**Comment by borine** [comment] 2020-04-24 08:58
see my comment to a previous issue here : https://github.com/Arkq/bluez-alsa/issues/250#issuecomment-607094063

**Comment by Arkq** [comment] 2021-01-16 22:44
Duplicate of #250.

**Closed by Arkq** 2021-01-16 22:44 UTC
